# Generated by Django 5.2 on 2025-10-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('M', 32), ('L', 42), ('XL', 64)], default='M', max_length=4),
        ),
    ]
