# Generated by Django 5.2 on 2025-10-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('None', 'None'), ('M', 32), ('L', 42), ('XL', 64)], default='None', max_length=4),
        ),
    ]
